version: '3'
services:
  redis:
    image: "redis:alpine"
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qpalzm
      POSTGRES_DB: ge-clicker-backend
    image: "postgres:alpine"
  api:
    build:
      args:
        tag: ge-clicker-backend
      context: .
    depends_on:
      - postgres
      - redis
    env_file: .env.dev
    command: python backend/manage.py runserver 0:8080
    ports:
      - "4000:8080"
    volumes:
     - .:/app
